import { NextResponse } from "next/server"
import { insertRecipe, getRecipes } from "@/lib/db"

export const dynamic = "force-dynamic"

const SEED_RECIPES = [
  {
    title: "GF Chicken Stir Fry",
    category: "dinner",
    is_gluten_free: true,
    prep_time_mins: 15,
    cook_time_mins: 15,
    servings: 4,
    description: "A quick and colourful stir fry using tamari instead of soy sauce. Ready in 30 minutes.",
    ingredients: [
      { name: "Chicken breast", quantity: "500", unit: "g", aisle: "meat-seafood", is_gluten_free: true },
      { name: "Broccoli", quantity: "1", unit: "head", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Capsicum", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Carrot", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Tamari (GF soy sauce)", quantity: "3", unit: "tbsp", aisle: "health-foods", is_gluten_free: true },
      { name: "Sesame oil", quantity: "1", unit: "tbsp", aisle: "international", is_gluten_free: true },
      { name: "Garlic", quantity: "3", unit: "cloves", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Ginger", quantity: "1", unit: "tbsp", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Rice", quantity: "2", unit: "cups", aisle: "pantry", is_gluten_free: true },
    ],
    instructions: "1. Cook rice according to packet directions.\n2. Slice chicken into strips. Dice veggies.\n3. Heat sesame oil in a wok over high heat.\n4. Cook chicken 5 min until golden. Remove.\n5. Stir fry veggies 3-4 min until tender-crisp.\n6. Return chicken, add tamari, garlic and ginger.\n7. Toss 1 min and serve over rice.",
    tags: ["quick", "asian", "kid-friendly"],
  },
  {
    title: "GF Lunchbox Sushi Bowls",
    category: "school-lunch",
    is_gluten_free: true,
    prep_time_mins: 20,
    cook_time_mins: 15,
    servings: 4,
    description: "Deconstructed sushi in a lunchbox — rice, cucumber, avocado, tuna and nori strips.",
    ingredients: [
      { name: "Sushi rice", quantity: "2", unit: "cups", aisle: "international", is_gluten_free: true },
      { name: "Rice wine vinegar", quantity: "2", unit: "tbsp", aisle: "international", is_gluten_free: true },
      { name: "Tinned tuna", quantity: "2", unit: "tins", aisle: "pantry", is_gluten_free: true },
      { name: "Cucumber", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Avocado", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Nori sheets", quantity: "4", unit: "", aisle: "international", is_gluten_free: true },
      { name: "Tamari", quantity: "2", unit: "tbsp", aisle: "health-foods", is_gluten_free: true },
      { name: "Sesame seeds", quantity: "1", unit: "tbsp", aisle: "international", is_gluten_free: true },
    ],
    instructions: "1. Cook sushi rice, stir through vinegar, cool.\n2. Dice cucumber and avocado.\n3. Drain tuna.\n4. Cut nori into strips with scissors.\n5. Layer rice, tuna, cucumber, avocado in lunchboxes.\n6. Top with nori strips and sesame seeds.\n7. Pack tamari in a small container for dipping.",
    tags: ["lunchbox", "no-cook-assembly", "kid-friendly"],
  },
  {
    title: "Slow-Cooked Lamb Shoulder",
    category: "fancy",
    is_gluten_free: true,
    prep_time_mins: 20,
    cook_time_mins: 300,
    servings: 6,
    description: "Melt-in-your-mouth lamb shoulder with rosemary and garlic. Perfect for a Sunday roast or dinner party.",
    ingredients: [
      { name: "Lamb shoulder", quantity: "1.5", unit: "kg", aisle: "meat-seafood", is_gluten_free: true },
      { name: "Garlic", quantity: "1", unit: "head", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Rosemary", quantity: "4", unit: "sprigs", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Olive oil", quantity: "3", unit: "tbsp", aisle: "pantry", is_gluten_free: true },
      { name: "Lemon", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Potatoes", quantity: "1", unit: "kg", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Chicken stock", quantity: "1", unit: "cup", aisle: "pantry", is_gluten_free: true },
      { name: "Salt & pepper", quantity: "", unit: "", aisle: "pantry", is_gluten_free: true },
    ],
    instructions: "1. Preheat oven to 160°C.\n2. Score lamb and insert garlic slices and rosemary into cuts.\n3. Rub with olive oil, lemon juice, salt and pepper.\n4. Place lamb on potatoes in a roasting pan.\n5. Pour stock around (not over) the lamb.\n6. Cover tightly with foil.\n7. Roast 5 hours until falling apart.\n8. Remove foil last 30 min to crisp.\n9. Rest 15 min, then pull apart with forks.",
    tags: ["slow-cook", "roast", "dinner-party", "impressive"],
  },
  {
    title: "Veggie Rice Paper Rolls",
    category: "school-lunch",
    is_gluten_free: true,
    prep_time_mins: 25,
    cook_time_mins: 0,
    servings: 4,
    description: "Fresh, crunchy GF rice paper rolls packed with veggies. Great for lunchboxes with a peanut dipping sauce.",
    ingredients: [
      { name: "Rice paper wrappers", quantity: "12", unit: "", aisle: "international", is_gluten_free: true },
      { name: "Carrot", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Cucumber", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Capsicum", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Lettuce", quantity: "1", unit: "bunch", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Rice vermicelli", quantity: "100", unit: "g", aisle: "international", is_gluten_free: true },
      { name: "Peanut butter", quantity: "3", unit: "tbsp", aisle: "pantry", is_gluten_free: true },
      { name: "Tamari", quantity: "1", unit: "tbsp", aisle: "health-foods", is_gluten_free: true },
      { name: "Lime", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
    ],
    instructions: "1. Cook vermicelli per packet, drain and cool.\n2. Julienne carrot, cucumber and capsicum.\n3. Dip rice paper in warm water until soft (5 sec).\n4. Lay on a board, add lettuce, veggies and noodles.\n5. Fold sides in, then roll tightly.\n6. Mix peanut butter, tamari and lime juice for dipping sauce.\n7. Wrap rolls individually in cling wrap for lunchbox.",
    tags: ["no-cook", "lunchbox", "vegan", "fresh"],
  },
  {
    title: "Beef Bolognese (GF)",
    category: "dinner",
    is_gluten_free: true,
    prep_time_mins: 15,
    cook_time_mins: 45,
    servings: 6,
    description: "Classic Aussie spag bol made GF with rice pasta. The whole family will love it.",
    ingredients: [
      { name: "Beef mince", quantity: "500", unit: "g", aisle: "meat-seafood", is_gluten_free: true },
      { name: "Onion", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Garlic", quantity: "3", unit: "cloves", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Carrot", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Celery", quantity: "2", unit: "stalks", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Tinned tomatoes", quantity: "2", unit: "tins", aisle: "pantry", is_gluten_free: true },
      { name: "Tomato paste", quantity: "2", unit: "tbsp", aisle: "pantry", is_gluten_free: true },
      { name: "GF pasta", quantity: "400", unit: "g", aisle: "health-foods", is_gluten_free: true },
      { name: "Parmesan", quantity: "50", unit: "g", aisle: "dairy-eggs", is_gluten_free: true },
      { name: "Olive oil", quantity: "2", unit: "tbsp", aisle: "pantry", is_gluten_free: true },
    ],
    instructions: "1. Heat oil, cook diced onion, garlic, carrot and celery 5 min.\n2. Add mince, break up and brown 5 min.\n3. Add tinned tomatoes and paste. Season.\n4. Simmer 30-40 min on low, stirring occasionally.\n5. Cook GF pasta per packet directions.\n6. Serve bol over pasta with grated parmesan.",
    tags: ["family-favourite", "freezer-friendly", "batch-cook"],
  },
  {
    title: "GF Banana Pancakes",
    category: "school-lunch",
    is_gluten_free: true,
    prep_time_mins: 5,
    cook_time_mins: 10,
    servings: 4,
    description: "3-ingredient pancakes that work as a snack or lunchbox treat. GF, dairy-free optional.",
    ingredients: [
      { name: "Bananas (ripe)", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Eggs", quantity: "2", unit: "", aisle: "dairy-eggs", is_gluten_free: true },
      { name: "GF oats", quantity: "0.5", unit: "cup", aisle: "health-foods", is_gluten_free: true },
      { name: "Cinnamon", quantity: "0.5", unit: "tsp", aisle: "pantry", is_gluten_free: true },
      { name: "Butter", quantity: "1", unit: "tbsp", aisle: "dairy-eggs", is_gluten_free: true },
    ],
    instructions: "1. Mash bananas in a bowl.\n2. Whisk in eggs and cinnamon.\n3. Blend in oats (or stir if you like chunky).\n4. Heat butter in a pan over medium.\n5. Drop spoonfuls of batter, cook 2 min each side.\n6. Cool and pack in lunchbox with a drizzle of honey.",
    tags: ["quick", "snack", "lunchbox", "3-ingredient"],
  },
  {
    title: "Salmon with Sweet Potato Mash",
    category: "dinner",
    is_gluten_free: true,
    prep_time_mins: 10,
    cook_time_mins: 25,
    servings: 4,
    description: "Pan-seared salmon on creamy sweet potato mash with steamed greens. Naturally GF and delicious.",
    ingredients: [
      { name: "Salmon fillets", quantity: "4", unit: "", aisle: "meat-seafood", is_gluten_free: true },
      { name: "Sweet potato", quantity: "800", unit: "g", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Butter", quantity: "2", unit: "tbsp", aisle: "dairy-eggs", is_gluten_free: true },
      { name: "Broccoli", quantity: "1", unit: "head", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Lemon", quantity: "1", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Olive oil", quantity: "1", unit: "tbsp", aisle: "pantry", is_gluten_free: true },
      { name: "Salt & pepper", quantity: "", unit: "", aisle: "pantry", is_gluten_free: true },
    ],
    instructions: "1. Peel and cube sweet potato. Boil 15 min until soft.\n2. Mash with butter, season well.\n3. Pat salmon dry, season with salt and pepper.\n4. Heat oil in a pan, cook salmon skin-down 4 min.\n5. Flip and cook 3 min more.\n6. Steam broccoli 4 min.\n7. Serve salmon on mash with broccoli and lemon wedges.",
    tags: ["healthy", "omega-3", "quick"],
  },
  {
    title: "Chicken Tacos (GF Corn Tortillas)",
    category: "dinner",
    is_gluten_free: true,
    prep_time_mins: 15,
    cook_time_mins: 15,
    servings: 4,
    description: "Build-your-own taco night! Using corn tortillas makes these naturally GF.",
    ingredients: [
      { name: "Chicken thighs", quantity: "600", unit: "g", aisle: "meat-seafood", is_gluten_free: true },
      { name: "Corn tortillas", quantity: "12", unit: "", aisle: "international", is_gluten_free: true },
      { name: "Avocado", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Tomato", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Lettuce", quantity: "1", unit: "head", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Lime", quantity: "2", unit: "", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Cumin", quantity: "1", unit: "tsp", aisle: "pantry", is_gluten_free: true },
      { name: "Paprika", quantity: "1", unit: "tsp", aisle: "pantry", is_gluten_free: true },
      { name: "Sour cream", quantity: "200", unit: "ml", aisle: "dairy-eggs", is_gluten_free: true },
    ],
    instructions: "1. Dice chicken, toss with cumin, paprika, salt, lime juice.\n2. Cook in a hot pan 6-8 min until charred.\n3. Warm tortillas in a dry pan or microwave.\n4. Dice tomato and avocado. Shred lettuce.\n5. Set up a taco bar — everyone builds their own!\n6. Top with sour cream and extra lime.",
    tags: ["family-favourite", "fun", "taco-tuesday", "interactive"],
  },
  {
    title: "Spaghetti Carbonara",
    category: "dinner",
    is_gluten_free: false,
    prep_time_mins: 10,
    cook_time_mins: 15,
    servings: 4,
    description: "Classic creamy carbonara. Contains gluten (regular pasta) — swap to GF pasta for a GF version.",
    ingredients: [
      { name: "Spaghetti", quantity: "400", unit: "g", aisle: "pantry", is_gluten_free: false },
      { name: "Bacon", quantity: "200", unit: "g", aisle: "meat-seafood", is_gluten_free: true },
      { name: "Eggs", quantity: "4", unit: "", aisle: "dairy-eggs", is_gluten_free: true },
      { name: "Parmesan", quantity: "100", unit: "g", aisle: "dairy-eggs", is_gluten_free: true },
      { name: "Garlic", quantity: "2", unit: "cloves", aisle: "fruit-veg", is_gluten_free: true },
      { name: "Black pepper", quantity: "1", unit: "tsp", aisle: "pantry", is_gluten_free: true },
    ],
    instructions: "1. Cook spaghetti per packet in salted water.\n2. Dice bacon, fry until crispy. Add garlic last minute.\n3. Whisk eggs with parmesan and pepper.\n4. Drain pasta, reserve 1 cup pasta water.\n5. Toss hot pasta with bacon off the heat.\n6. Pour egg mixture over, toss quickly (residual heat cooks eggs).\n7. Add pasta water if needed for creaminess.\n\nGF TIP: Use GF spaghetti for a gluten-free version.",
    tags: ["classic", "quick", "comfort-food"],
  },
  {
    title: "GF Chicken Nuggets",
    category: "school-lunch",
    is_gluten_free: true,
    prep_time_mins: 15,
    cook_time_mins: 20,
    servings: 4,
    description: "Crunchy homemade chicken nuggets coated in GF breadcrumbs. Way better than store-bought!",
    ingredients: [
      { name: "Chicken breast", quantity: "500", unit: "g", aisle: "meat-seafood", is_gluten_free: true },
      { name: "GF breadcrumbs", quantity: "1", unit: "cup", aisle: "health-foods", is_gluten_free: true },
      { name: "Parmesan", quantity: "50", unit: "g", aisle: "dairy-eggs", is_gluten_free: true },
      { name: "Eggs", quantity: "2", unit: "", aisle: "dairy-eggs", is_gluten_free: true },
      { name: "GF flour", quantity: "0.5", unit: "cup", aisle: "health-foods", is_gluten_free: true },
      { name: "Paprika", quantity: "1", unit: "tsp", aisle: "pantry", is_gluten_free: true },
      { name: "Olive oil spray", quantity: "1", unit: "", aisle: "pantry", is_gluten_free: true },
    ],
    instructions: "1. Preheat oven to 200°C. Line tray with baking paper.\n2. Cut chicken into nugget-sized pieces.\n3. Set up 3 bowls: GF flour, beaten eggs, breadcrumbs mixed with parmesan and paprika.\n4. Coat chicken: flour → egg → crumbs.\n5. Place on tray, spray with olive oil.\n6. Bake 20 min, flipping halfway.\n7. Cool and pack for lunchbox with dipping sauce.",
    tags: ["lunchbox", "kid-favourite", "baked-not-fried"],
  },
]

export async function POST() {
  const existing = await getRecipes()
  if (existing.length > 0) {
    return NextResponse.json({ message: `Already have ${existing.length} recipes, skipping seed.` })
  }

  const results = []
  for (const recipe of SEED_RECIPES) {
    const saved = await insertRecipe(recipe)
    results.push(saved.title)
  }

  return NextResponse.json({ message: `Seeded ${results.length} recipes`, recipes: results })
}
